### ISSUE TITLE
Falar com a câmara

### ISSUE THREAD

**Issue by inesdemariajorge** [miguelriemoliveira/psa_21-22_tp2#4]

**Comment by miguelriemoliveira** [comment]
I know opencv is used to communicate with cameras ...

**Comment by miguelriemoliveira** [comment]
Found this klink which should have everything we need 

https://www.geeksforgeeks.org/python-opencv-capture-video-from-camera/

**Comment by miguelriemoliveira** [comment]
Closing via 51ba26b63e8bef3f50cd932d281d83f5b2c49d62
